---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-deployment
  namespace: webapp
  labels:
    app: board
spec:
  replicas: 1
  selector:
    matchLabels:
      app: board
  template:
    metadata:
      namespace: webapp
      labels:
        app: board
    spec:
      containers:
        - name: board-app-cntr
          image: pushkar4399/boardgamewebapp:latest
          ports:
          - containerPort: 8080
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: board-service
  namespace: webapp

spec:
  type: NodePort
  selector:
    app: board
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30005
